version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/janisgarklavs/tournament/
    depends_on:
      - db
    links:
      - "db:database"
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example